"""Add email to students

Revision ID: 86db4d5e3869
Revises: c0a445380e3e
Create Date: 2025-08-05 19:37:21.791710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86db4d5e3869'
down_revision = 'c0a445380e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_students')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint("StudentEmailUK", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint("StudentEmailUK", type_='unique')
        batch_op.drop_column('email')

    op.create_table('_alembic_tmp_students',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='StudentEmailUK')
    )
    # ### end Alembic commands ###
