"""Add boarding house FK

Revision ID: cdabb7694377
Revises: f4fbab28671a
Create Date: 2025-08-07 19:59:22.438747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdabb7694377'
down_revision = 'f4fbab28671a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boarding_house', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("StudentBoardingHouseFK", 'boarding_houses', ['boarding_house'], ['id'])
        batch_op.create_check_constraint("AgeGreaterEqual18", "age >= 5")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint("StudentBoardingHouseFK", type_='foreignkey')
        batch_op.drop_constraint("AgeGreaterEqual18")
        batch_op.drop_column('boarding_house')

    # ### end Alembic commands ###
