"""Add student reg number

Revision ID: ef6439a796bc
Revises: f4fbab28671a
Create Date: 2025-08-05 19:59:58.749670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
import uuid



# revision identifiers, used by Alembic.
revision = 'ef6439a796bc'
down_revision = 'f4fbab28671a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_code', sa.String(length=200), nullable=True))

        students = table("students", column("id", sa.Integer), column("reg_code", sa.String))
        conn = batch_op.get_bind()
        results = conn.execute(sa.text("SELECT id FROM students WHERE reg_code IS NULL"))
        for row in results:
            tmp_reg = f"{uuid.uuid4()}.fake_reg"
            conn.execute(
                sa.text("UPDATE students SET reg_code = :reg_code WHERE id = :id"),
                { "reg_code":tmp_reg, "id":row.id }
                )
        
        batch_op.alter_column("reg_code", nullable=False)
        batch_op.create_unique_constraint("StudentRegNoUK", ['reg_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint("StudentRegNoUK", type_='unique')
        batch_op.drop_column('reg_code')

    # ### end Alembic commands ###
